version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Update Apk
          command: |
            apk update
            apk upgrade
      - run:
          name: Install Bash
          command: |
            apk add bash 
      - run:
          name: Install Git 
          command: |
            apk add git 
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived 
          command: |
            ls -al
            echo '^^^That should look familiar^^^' 
